mysql-connect:
  username: 'dfw'
  password: '^52]pt*xz+g^03_C#YHb'

  ipv4: '127.0.0.1'
  port: '3306'
  db-name: 'xfw'

cqhttp-ws-connect:
  ipv4: '127.0.0.1'
  port: '6700'
  secret: 'CQHTTP_SECRET'

poem-file-path: '../share/poem'

group-enable-send-randomgck:
  - 929027715

group-enable-homo-space:
  - 929027715

user-black-list:
  - 0
